# Generated by Django 3.1.3 on 2020-11-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0004_auto_20201130_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time_stamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
