# Generated by Django 3.1.3 on 2020-11-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0006_remove_transactionlog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='time_stamp',
        ),
    ]
