# Generated by Django 3.1.3 on 2020-12-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0008_auto_20201201_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='block',
            new_name='start_block',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='end_block',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
