# Generated by Django 3.1.3 on 2020-12-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0009_auto_20201201_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
