# Generated by Django 3.1.3 on 2020-12-02 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0010_auto_20201201_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ethbalancelog',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date format: %Y-%m-%d'),
        ),
    ]
