# Generated by Django 3.1.3 on 2020-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0011_auto_20201202_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
    ]
