# Generated by Django 3.1.3 on 2020-12-03 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0013_account_tokenbalancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date format: %Y-%m-%d'),
        ),
    ]
