# Generated by Django 3.1.3 on 2020-12-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0014_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contract_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
