# Generated by Django 3.1.3 on 2020-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherView', '0015_account_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='Account address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='contract_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Smart contract address'),
        ),
    ]
